### ISSUE TITLE
Line break between tag name and first attribute

### ISSUE THREAD

**Issue by fvsch** [jenstornell/kirby-html-minifier#1]
I get results looking like this:

``` html
<span
class="MainNav-item MainNav-item--cat">
<a
href="/code/">Code</a>
</span>
```

The space between the tag name and the first attribute is always replaced by a new line, in the whole HTML response. Is that on purpose?

**Comment by jenstornell** [comment]
I don't know. I'm using the same HTML minifier as https://github.com/ian-cox/Kirby-MinifyHTML which is https://github.com/mrclay/minify. They still works differently and I suspect I'm using a newer version of it.

Somewhere on the web I read that it's not good to minify everything like just one line. I don't remember the reason but maybe that's what they have been trying to fix, linebreaks.

I don't see it as a big issue because the code still works and it's minified, but I see the need for changing the parser somehow. There are two ways to do that:

1. Add a few more HTML parsers and select one by a config value (c::set).
1. Add a path to an alternative parser to run.

The first is easier for the user but the second one gives more options.

**Comment by jenstornell** [comment]
@fvsch I've updated the plugin with a another html minify engine.
